# Iterate
int64 k

# Initial conditions
std_msgs/Float64MultiArray x0

# Base reference speed
std_msgs/Float64MultiArray base_vel_ref

---
# The solver has been run successfully
bool run_success

# Gait
std_msgs/Float64MultiArray gait

# Start state used
std_msgs/Float64MultiArray xs

# Solution
std_msgs/Float64MultiArray us

# Feedback gains
std_msgs/Float64MultiArray K

# Some info about the solve
float64 solving_duration
int64 num_iters
